# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    tags:
      - "v*"
    branches:
      - master
  release:
    types: [created]

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@ppjmpd'
      # Removes the `version` key from a `package-lock.json`
      - uses: mrauhu/deversion@v1
      # Now you have same key if the dependencies is haven't changed
      - uses: actions/cache@v2
        id: modules-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
      # Install if dependencies is changed or cache expired
      - if: steps.modules-cache.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm test
      - run: npm build
      # Publish only if the `v*` tag
      # via Github Packages
      - if: startsWith(github.ref, 'refs/tags/v')
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      # Change registry URL
      - if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          scope: '@ppjmpd'
      # and publish via NPM with public access
      - if: startsWith(github.ref, 'refs/tags/v')
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
